# Generated by Django 5.2.16 on 2026-07-14 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_cycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_sessions', to='trivia_app.mastercycle')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_choice', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('trivia_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trivia_app.triviasession')),
            ],
        ),
        migrations.CreateModel(
            name='TrophyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Correct trivia answer', max_length=255)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('trivia_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_awards', to='trivia_app.triviasession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trivia_session', 'user'), name='unique_trophy_per_user_session')],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('trivia_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia_app.triviaquestion')),
                ('trivia_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia_app.triviasession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trivia_session', 'trivia_question', 'user'), name='unique_user_answer_per_question')],
            },
        ),
    ]
