# Generated by Django 5.2.16 on 2026-07-22 19:18

from datetime import timedelta

from django.db import migrations, models


def populate_ranking_and_generation_data(apps, schema_editor):
    TriviaSession = apps.get_model('trivia_app', 'TriviaSession')
    TrophyAward = apps.get_model('trivia_app', 'TrophyAward')
    UserAnswer = apps.get_model('trivia_app', 'UserAnswer')

    for session in TriviaSession.objects.exclude(publish_at=None):
        if session.publish_at <= session.created_at + timedelta(minutes=1):
            session.generation_method = 'ai'
            session.save(update_fields=['generation_method'])

    for trophy in TrophyAward.objects.all():
        answer = UserAnswer.objects.filter(
            trivia_session_id=trophy.trivia_session_id,
            user_id=trophy.user_id,
            is_correct=True,
        ).order_by('submitted_at').first()
        trophy.answered_at = answer.submitted_at if answer else trophy.awarded_at
        trophy.save(update_fields=['answered_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0006_mastercycle_daily_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviasession',
            name='generation_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='trophyaward',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_ranking_and_generation_data, migrations.RunPython.noop),
    ]
