from django.urls import path

from .api import (
    auth_logout,
    auth_me,
    auth_request_code,
    auth_verify_code,
    leaderboard_view,
    master_cycle_create_trivia,
    master_cycle_generate_trivia,
    master_cycle_list_create,
    notification_list_update,
    platform_admin_update,
    platform_overview,
    team_join,
    team_list_create,
    team_manage,
    team_members,
    team_membership_manage,
    team_analytics,
    trivia_session_answers,
    trivia_session_evaluate,
    trivia_session_publish,
    trivia_session_retrieve,
    trivia_session_update,
    user_delete,
    user_list_create,
)
from .api.common import health_check


urlpatterns = [
    path('health/', health_check, name='health-check'),
    path('auth/request-code/', auth_request_code, name='auth-request-code'),
    path('auth/verify-code/', auth_verify_code, name='auth-verify-code'),
    path('auth/me/', auth_me, name='auth-me'),
    path('auth/logout/', auth_logout, name='auth-logout'),
    path('users/', user_list_create, name='user-list-create'),
    path('users/<int:pk>/', user_delete, name='user-delete'),
    path('admin/users/<int:pk>/', platform_admin_update, name='platform-admin-update'),
    path('admin/overview/', platform_overview, name='platform-overview'),
    path('teams/', team_list_create, name='team-list-create'),
    path('teams/<int:pk>/', team_manage, name='team-manage'),
    path('teams/join/', team_join, name='team-join'),
    path('teams/<int:pk>/members/', team_members, name='team-members'),
    path('teams/<int:pk>/analytics/', team_analytics, name='team-analytics'),
    path('teams/<int:team_pk>/members/<int:membership_pk>/', team_membership_manage, name='team-membership-manage'),
    path('leaderboard/', leaderboard_view, name='leaderboard'),
    path('notifications/', notification_list_update, name='notification-list-update'),
    path('master-cycles/', master_cycle_list_create, name='master-cycle-list-create'),
    path('master-cycles/<int:pk>/generate-trivia/', master_cycle_generate_trivia, name='master-cycle-generate-trivia'),
    path('master-cycles/<int:pk>/trivia-sessions/', master_cycle_create_trivia, name='master-cycle-create-trivia'),
    path('trivia-sessions/<int:pk>/', trivia_session_retrieve, name='trivia-session-retrieve'),
    path('trivia-sessions/<int:pk>/edit/', trivia_session_update, name='trivia-session-update'),
    path('trivia-sessions/<int:pk>/publish/', trivia_session_publish, name='trivia-session-publish'),
    path('trivia-sessions/<int:pk>/evaluate/', trivia_session_evaluate, name='trivia-session-evaluate'),
    path('trivia-sessions/<int:pk>/answers/', trivia_session_answers, name='trivia-session-answers'),
]
